pipeline:
  run-mongo-tests:
    image: node:8.2
    commands:
      - sleep 5
      - ./bin/run.sh
    when:
      status: [ failure, success ]
      event: [pull_request]

  publish-node-mongo:
    image: plugins/npm
    secrets: [ npm_username, npm_email, npm_password ]
    when:
      event: [ tag ]
      branches: [ master ]

services:
  mongo:
    image: mongo:3.4
branches: [ master, "*:master" ]
